[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
raffle = "BYhrkv1yPFJrtyKbL5UBF2GvabQw3His9tF5AV2JgzRy"

[programs.devnet]
raffle = "BYhrkv1yPFJrtyKbL5UBF2GvabQw3His9tF5AV2JgzRy"

[programs.mainnet]
raffle = "BYhrkv1yPFJrtyKbL5UBF2GvabQw3His9tF5AV2JgzRy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

# Clone Metaplex Token Metadata program for local testing
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

# Clone Token program
[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

# Clone SPL Associated Token Account program
[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
